services:

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   environment:
  #     RAILS_ENV: production
  #     TESLA_PROXY_URL: https://tesla_http_proxy:4443
  #   env_file:
  #     - .env
  #   volumes:
  #     - sqlite_db:/rails/db
  #   restart: unless-stopped

  tesla_http_proxy:
    image: tesla/vehicle-command:latest
    ports:
      - "4443:4443"
    environment:
      - TESLA_HTTP_PROXY_TLS_CERT=/config/tls-cert.pem
      - TESLA_HTTP_PROXY_TLS_KEY=/config/tls-key.pem
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=4443
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/config/fleet-key.pem
      - TESLA_VERBOSE=true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./vehicle-command/config:/config

  app:
    build:
      context: ./fleet-telemetry
    ports:
      - 0.0.0.0:443:443
    volumes:
      - /root/certs:/config
      - ./config.json:/etc/fleet-telemetry/config.json
    environment:
      - STRAVOLT_API_ENDPOINT
      - STRAVOLT_BEARER_TOKEN

volumes:
  sqlite_db:
